{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from xgboost import XGBRegressor\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "import numpy as np\n",
    "\n",
    "# 데이터 로드\n",
    "train_data = pd.read_csv('./train.csv')\n",
    "test_data = pd.read_csv('./test.csv')\n",
    "\n",
    "# 결측치 처리\n",
    "train_data['강수량(mm)'].fillna(0, inplace=True)\n",
    "train_data['풍속(m/s)'].fillna(train_data['풍속(m/s)'].mean(), inplace=True)\n",
    "train_data['습도(%)'].fillna(train_data['습도(%)'].mean(), inplace=True)\n",
    "train_data['일조(hr)'].fillna(0, inplace=True)\n",
    "train_data['일사(MJ/m2)'].fillna(0, inplace=True)\n",
    "test_data['강수량(mm)'].fillna(0, inplace=True)\n",
    "test_data['일조(hr)'] = 0\n",
    "test_data['일사(MJ/m2)'] = 0\n",
    "\n",
    "\n",
    "# 날짜 및 시간 특성 파생\n",
    "train_data['일시'] = pd.to_datetime(train_data['일시'], format='%Y%m%d %H')\n",
    "test_data['일시'] = pd.to_datetime(test_data['일시'], format='%Y%m%d %H')\n",
    "train_data['연'] = train_data['일시'].dt.year\n",
    "train_data['월'] = train_data['일시'].dt.month\n",
    "train_data['일'] = train_data['일시'].dt.day\n",
    "train_data['시간'] = train_data['일시'].dt.hour\n",
    "test_data['연'] = test_data['일시'].dt.year\n",
    "test_data['월'] = test_data['일시'].dt.month\n",
    "test_data['일'] = test_data['일시'].dt.day\n",
    "test_data['시간'] = test_data['일시'].dt.hour\n",
    "\n",
    "# 필요하지 않은 컬럼 제거\n",
    "train_data.drop(columns=['num_date_time', '일시'], inplace=True)\n",
    "test_data.drop(columns=['num_date_time', '일시'], inplace=True)\n",
    "\n",
    "# 특성과 라벨 분리\n",
    "X_train = train_data.drop(columns=['전력소비량(kWh)'])\n",
    "y_train = train_data['전력소비량(kWh)']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 데이터 정규화\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train)\n",
    "X_test_scaled = scaler.transform(test_data)\n",
    "\n",
    "# 데이터 분할 (훈련 및 검증 세트)\n",
    "X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(X_train_scaled, y_train, test_size=0.2, random_state=42)\n",
    "\n",
    "# 하이퍼파라미터 그리드 정의\n",
    "param_grid = {\n",
    "    'learning_rate': [0.01, 0.05, 0.1],\n",
    "    'max_depth': [3, 5, 7],\n",
    "    'n_estimators': [5000],\n",
    "    'subsample': [0.7, 0.9],\n",
    "    'colsample_bytree': [0.7, 0.9],\n",
    "}\n",
    "\n",
    "# XGBoost 모델 생성\n",
    "xgb_model = XGBRegressor(objective='reg:squarederror', random_state=42,tree_method='gpu_hist')\n",
    "\n",
    "# 그리드 서치 객체 생성\n",
    "grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid,\n",
    "                           cv=3,  verbose=2, scoring='neg_root_mean_squared_error')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 5 folds for each of 36 candidates, totalling 180 fits\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.2s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.2s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.7, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.01, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.05, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=3, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=5, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.7; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n",
      "[CV] END colsample_bytree=0.9, learning_rate=0.1, max_depth=7, n_estimators=5000, subsample=0.9; total time=   0.1s\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "\nAll the 180 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n2 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:23:56] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n14 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:23:57] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n17 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:23:58] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n18 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:23:59] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n18 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:00] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n15 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:01] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n18 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:02] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n18 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:03] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n17 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:04] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n14 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:05] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n16 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:06] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n13 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:07] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[13], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m# 그리드 서치 수행\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m grid_search\u001b[39m.\u001b[39mfit(X_train_split, y_train_split, eval_set\u001b[39m=\u001b[39m[(X_val_split, y_val_split)], early_stopping_rounds\u001b[39m=\u001b[39m\u001b[39m10\u001b[39m, verbose\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)\n\u001b[1;32m      4\u001b[0m \u001b[39m# 최적의 하이퍼파라미터 출력\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mBest Hyperparameters:\u001b[39m\u001b[39m\"\u001b[39m, grid_search\u001b[39m.\u001b[39mbest_params_)\n",
      "File \u001b[0;32m/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_search.py:874\u001b[0m, in \u001b[0;36mBaseSearchCV.fit\u001b[0;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[1;32m    868\u001b[0m     results \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_format_results(\n\u001b[1;32m    869\u001b[0m         all_candidate_params, n_splits, all_out, all_more_results\n\u001b[1;32m    870\u001b[0m     )\n\u001b[1;32m    872\u001b[0m     \u001b[39mreturn\u001b[39;00m results\n\u001b[0;32m--> 874\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_run_search(evaluate_candidates)\n\u001b[1;32m    876\u001b[0m \u001b[39m# multimetric is determined here because in the case of a callable\u001b[39;00m\n\u001b[1;32m    877\u001b[0m \u001b[39m# self.scoring the return type is only known after calling\u001b[39;00m\n\u001b[1;32m    878\u001b[0m first_test_score \u001b[39m=\u001b[39m all_out[\u001b[39m0\u001b[39m][\u001b[39m\"\u001b[39m\u001b[39mtest_scores\u001b[39m\u001b[39m\"\u001b[39m]\n",
      "File \u001b[0;32m/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_search.py:1388\u001b[0m, in \u001b[0;36mGridSearchCV._run_search\u001b[0;34m(self, evaluate_candidates)\u001b[0m\n\u001b[1;32m   1386\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_run_search\u001b[39m(\u001b[39mself\u001b[39m, evaluate_candidates):\n\u001b[1;32m   1387\u001b[0m \u001b[39m    \u001b[39m\u001b[39m\"\"\"Search all candidates in param_grid\"\"\"\u001b[39;00m\n\u001b[0;32m-> 1388\u001b[0m     evaluate_candidates(ParameterGrid(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mparam_grid))\n",
      "File \u001b[0;32m/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_search.py:851\u001b[0m, in \u001b[0;36mBaseSearchCV.fit.<locals>.evaluate_candidates\u001b[0;34m(candidate_params, cv, more_results)\u001b[0m\n\u001b[1;32m    844\u001b[0m \u001b[39melif\u001b[39;00m \u001b[39mlen\u001b[39m(out) \u001b[39m!=\u001b[39m n_candidates \u001b[39m*\u001b[39m n_splits:\n\u001b[1;32m    845\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\n\u001b[1;32m    846\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mcv.split and cv.get_n_splits returned \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    847\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39minconsistent results. Expected \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    848\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39msplits, got \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mformat(n_splits, \u001b[39mlen\u001b[39m(out) \u001b[39m/\u001b[39m\u001b[39m/\u001b[39m n_candidates)\n\u001b[1;32m    849\u001b[0m     )\n\u001b[0;32m--> 851\u001b[0m _warn_or_raise_about_fit_failures(out, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39merror_score)\n\u001b[1;32m    853\u001b[0m \u001b[39m# For callable self.scoring, the return type is only know after\u001b[39;00m\n\u001b[1;32m    854\u001b[0m \u001b[39m# calling. If the return type is a dictionary, the error scores\u001b[39;00m\n\u001b[1;32m    855\u001b[0m \u001b[39m# can now be inserted with the correct key. The type checking\u001b[39;00m\n\u001b[1;32m    856\u001b[0m \u001b[39m# of out will be done in `_insert_error_scores`.\u001b[39;00m\n\u001b[1;32m    857\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mcallable\u001b[39m(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mscoring):\n",
      "File \u001b[0;32m/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:367\u001b[0m, in \u001b[0;36m_warn_or_raise_about_fit_failures\u001b[0;34m(results, error_score)\u001b[0m\n\u001b[1;32m    360\u001b[0m \u001b[39mif\u001b[39;00m num_failed_fits \u001b[39m==\u001b[39m num_fits:\n\u001b[1;32m    361\u001b[0m     all_fits_failed_message \u001b[39m=\u001b[39m (\n\u001b[1;32m    362\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39mAll the \u001b[39m\u001b[39m{\u001b[39;00mnum_fits\u001b[39m}\u001b[39;00m\u001b[39m fits failed.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    363\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mIt is very likely that your model is misconfigured.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    364\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mYou can try to debug the error by setting error_score=\u001b[39m\u001b[39m'\u001b[39m\u001b[39mraise\u001b[39m\u001b[39m'\u001b[39m\u001b[39m.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    365\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mBelow are more details about the failures:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mfit_errors_summary\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    366\u001b[0m     )\n\u001b[0;32m--> 367\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(all_fits_failed_message)\n\u001b[1;32m    369\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    370\u001b[0m     some_fits_failed_message \u001b[39m=\u001b[39m (\n\u001b[1;32m    371\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mnum_failed_fits\u001b[39m}\u001b[39;00m\u001b[39m fits failed out of a total of \u001b[39m\u001b[39m{\u001b[39;00mnum_fits\u001b[39m}\u001b[39;00m\u001b[39m.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    372\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mThe score on these train-test partitions for these parameters\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    376\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mBelow are more details about the failures:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mfit_errors_summary\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    377\u001b[0m     )\n",
      "\u001b[0;31mValueError\u001b[0m: \nAll the 180 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n2 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:23:56] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n14 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:23:57] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n17 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:23:58] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n18 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:23:59] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n18 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:00] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n15 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:01] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n18 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:02] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n18 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:03] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n17 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:04] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n14 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:05] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n16 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:06] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n\n--------------------------------------------------------------------------------\n13 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/training.py\", line 180, in train\n    bst = cb_container.before_training(bst)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 148, in before_training\n    model = c.before_training(model=model)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/callback.py\", line 350, in before_training\n    self.starting_round = model.num_boosted_rounds()\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 2466, in num_boosted_rounds\n    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))\n  File \"/opt/miniconda3/envs/jw/lib/python3.11/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [17:24:07] /croot/xgboost-split_1675457761144/work/src/data/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0xc01d4) [0x7f7cb64c01d4]\n  [bt] (1) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x1aaf12) [0x7f7cb65aaf12]\n  [bt] (2) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters()+0xdd) [0x7f7cb6662e9d]\n  [bt] (3) /opt/miniconda3/envs/jw/lib/libxgboost.so(xgboost::gbm::GBTree::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x331) [0x7f7cb667a6d1]\n  [bt] (4) /opt/miniconda3/envs/jw/lib/libxgboost.so(+0x2a7ab2) [0x7f7cb66a7ab2]\n  [bt] (5) /opt/miniconda3/envs/jw/lib/libxgboost.so(XGBoosterBoostedRounds+0x2d) [0x7f7cb64c38ed]\n  [bt] (6) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0xa052) [0x7f7cf875e052]\n  [bt] (7) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(+0x8925) [0x7f7cf875c925]\n  [bt] (8) /opt/miniconda3/envs/jw/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7f7cf875d06e]\n\n\n"
     ]
    }
   ],
   "source": [
    "# 그리드 서치 수행\n",
    "grid_search.fit(X_train_split, y_train_split, eval_set=[(X_val_split, y_val_split)], early_stopping_rounds=10, verbose=True)\n",
    "\n",
    "# 최적의 하이퍼파라미터 출력\n",
    "print(\"Best Hyperparameters:\", grid_search.best_params_)\n",
    "\n",
    "# 검증 세트에서 최적 모델의 성능 평가\n",
    "y_val_pred_best = grid_search.best_estimator_.predict(X_val_split)\n",
    "val_rmse_best = np.sqrt(mean_squared_error(y_val_split, y_val_pred_best))\n",
    "print(\"Validation RMSE with Best Model:\", val_rmse_best)\n",
    "\n",
    "# test 데이터에 대한 예측\n",
    "y_test_pred_best = grid_search.best_estimator_.predict(X_test_scaled)\n",
    "test_predictions_best = pd.DataFrame({'전력소비량(kWh)': y_test_pred_best})\n",
    "test_predictions_best\n",
    "# test_predictions_best.to_csv('test_predictions_best.csv', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "jw",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
